makan =input("apakah kamu sudah makan: ")
belum_makan = "belum"
sudah_makan= "sudah"

if belum_makan == sudah_makan :
    print(f"jika {belum_makan} kamu harus makan selama 15 menit")
    
elif sudah_makan == belum_makan:
    print(f"jika {sudah_makan} kamu langsung mandi")

input("kita lanjut ke mandi")

mandi =input("apakah kamu sudah mandi: ")
belum_mandi = "belum"
sudah_mandi= "sudah"

if belum_mandi== sudah_mandi:
    print(f"jika {belum_mandi}kamu harus mandi selama 10 menit")

elif sudah_mandi == belum_mandi:
    print(f"jika {sudah_mandi} kamu langsung mandi")

input("sekarang naik transportasi")

transportasi =input(f"kamu menggunakan apa waktu erangkat sekolah: ", "jalan kaki/sepeda" ) 
sudah_mandi = "sudah"
